@startuml
'https://plantuml.com/sequence-diagram

autonumber
"Customer" -> psp : Authorize 1 cent transaction
psp -> mobyyou: account Info
mobyyou->"xpay Engine": add mandate
"xpay Engine"-> "User Service": add user account
"xpay Engine"-> "Mandate Service": add Mandate
mobyyou->"xpay Engine" : add Direct Debit Transaction
"xpay Engine"->"xpay Engine": execute Rules [validations ,fee calculation , interface selection , mandate info retreival]
"xpay Engine"->RaboISO20022: add direct debit transaction
"xpay Engine"->mobyyou: add direct debit (success))
RaboISO20022-->RaboISO20022 : create payment 008.001 file
RaboISO20022->Bank : batch payment file (scheduled job)
Bank-->Bank: process payment
Bank->RaboISO20022: Reporting Information
RaboISO20022-->RaboISO20022 : update transaction status
"xpay Engine"-> RaboISO20022 : get Transaction status
RaboISO20022-->"xpay Engine" : transaction status (success)


@enduml