spring:
  profiles:
    active: test  # Specify the active profile, e.g., 'dev' for development environment

  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: none
        hibernate:
          cache:
            use_second_level_cache: true  # Enable cache (optional)
            region:
              factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

  datasource:
    url: jdbc:postgresql://localhost:5432/mainhp
    username: postgres
    password: pgadmin
    driverClassName: org.postgresql.Driver

  sql:
    init:
      platform: postgres

  liquibase:
    contexts: local
    enabled: false
    change-log: db/changelog/db-changelog.yml

