openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /users/:
    post:
      summary: create a new user
      description: creates a new user with account details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userinformation'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: the collection IDs created.
                type: array
                items:
                  $ref: '#/components/schemas/Id'
        '400':
          $ref: '#/components/responses/400'



  /users/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      summary: Retrieve sepadd collection information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: Description of transaction ID
                type: array
                items:
                  $ref: '#/components/schemas/userinformation'
        '404':
          $ref: '#/components/responses/404'
components:
  parameters:
    id:
      name: id
      required: true
      in: path
      description: Object ID (UUID)
      schema:
        type: string
        format: uuid
  responses:
    '400':
      description: Invalid data submitted or request processing error
      content:
        application/json:
          schema:
            type: object

    '404':
      description: No such object
  schemas:
    Id:
      type: string
      maxLength: 36
      description: UUID
    userinformation:
      type: object
      properties:
        mandateId:
          type: string
          example: "124567"
        amount:
          type: number
          format: float
        currency:
          type: string
        collectiondate:
          readOnly: true
          description: Object creation time
          allOf:
            - $ref: '#/components/schemas/UnixTimestamp'

        status:
          type: string
    UnixTimestamp:
      type: integer
      format: Unix timestamp (seconds)
      example: 1619740800