/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.henripay.sepadd.controller;


import com.henripay.sepadd.dto.TransactionStatusResponse;
import com.henripay.sepadd.service.TransactionService;
import io.swagger.annotations.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;


import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;


@Service
@RestController

public class GetTransactionStatusApiImpl implements GetTransactionStatusApiDelegate {
    @Autowired
    private TransactionService transactionService;

    @Autowired
    public void GetTransactionService(TransactionService transactionService) {
        this.transactionService = transactionService;

    }

    /**
     * GET /getTransactionStatus : Get Transaction Status
     *
     * @param transactionId ID of the transaction (required)
     * @return Transaction status retrieved successfully (status code 200)
     */
    @ApiOperation(value = "Get Transaction Status", nickname = "getTransactionStatusGet", notes = "", response = TransactionStatusResponse.class, tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Transaction status retrieved successfully", response = TransactionStatusResponse.class)})
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/get-transaction-status",
            produces = {"application/json"}
    )
    public ResponseEntity<TransactionStatusResponse> getTransactionStatusGet(@NotNull @ApiParam(value = "ID of the transaction", required = true) @Valid @RequestParam(value = "transactionId", required = true) String transactionId) {
        TransactionStatusResponse status = transactionService.queryTransactionByTransactionId(transactionId);

        return new ResponseEntity<>(status, HttpStatus.OK);
    }

}
