@startuml
'https://plantuml.com/sequence-diagram
actor "Card Holder" as holder


entity "Mobyyou" as mobyyou
participant "xpay" as xpay

participant "Issuer" as issuer
holder->mobyyou: user enters account details
mobyyou-> issuer : initiate 1 cent iDeal transaction
mobyyou->mobyyou: create mandate
mobyyou->mobyyou : calculate amount [daily]
mobyyou->xpay : initiate sepadd /collection {mandateid , amount}
xpay->xpay: validators , business rules , add transaction to file
xpay-->mobyyou : {success}
xpay-->xpay : create payment 008.001 file
xpay-->Finxp : batch payment file (scheduled job)
Finxp--> Finxp : process batch file
Finxp->xpay: Report file
xpay->xpay : process reporting file , update transaction status
xpay-> mobyyou : send transaction status notification

xpay-->xpay : create payment 002.001 file  (CT transactions)
xpay-->Finxp : batch payment file (scheduled job)
Finxp-->Finxp : process payment order
Finxp -> xpay: Report File
xpay->xpay : process reporting file , update transaction status
xpay-> mobyyou : send transaction status notification


@enduml