@startuml
'https://plantuml.com/sequence-diagram
actor "Card Holder" as holder

entity "Mobyyou App" as mobyyou
participant "xpay" as xpay
participant "Acquirer" as acq
participant "Issuer" as issuer
holder->mobyyou: user enters credit card details
mobyyou->xpay : credit card details /purchase

xpay-> Network: tokenize card for recurrent payment
holder-> issuer: 3D secure verification
issuer-> xpay : 3D secure completed
xpay-> mobyyou : add credit card completed

xpay->acq : 0 euro transaction CIT
acq--> issuer: ISO100 authorization
issuer-> acq : ISO110 authorization response
mobyyou-> mobyyou : generate daily bill
mobyyou-> xpay : /charge {amount , userid }
xpay-> xpay: business rules
xpay-> acq: MIT transaction request {token , amount}
acq --> issuer : ISO100 authorization
issuer -> acq : ISO100 authorization
acq->xpay : MIT transaction response {sucess}
xpay-->mobyyou: transaction completion {sucess}

@enduml