@startuml
'https://plantuml.com/sequence-diagram
actor "Card Holder" as holder
entity "POS Terminal" as POS

entity "Mobyyou" as mobyyou
participant "xpay" as xpay
participant "Acquirer" as Acq
participant "Issuer" as issuer
holder->POS: user checks in to the Grab&Go store
POS-> xpay: Pre-Authentication {50 euro , mcc= grocery store}
xpay ->Acq:  Pre-Authentication
Acq -> issuer : ISO200 message [pre-auth]
issuer -> Acq : ISO210 message [approved]
Acq -> xpay: Pre-auth response
xpay-> mobyyou : Pre-auth response {transactionId, userid}
mobyyou--> mobyyou: calculate final amount
mobyyou->xpay: Pre-Auth completion {transactionId , final amount}
xpay->xpay: validators , business rules
xpay-> Acq:  Pre-Auth completion {pan , final amount}
Acq -> issuer: ISO220 message [pre-auth completion]
issuer-> Acq: ISO230 message [approved]
Acq --> xpay : Pre-Auth completion response
xpay-->mobyyou: transaction completion

@enduml