@startuml
'https://plantuml.com/sequence-diagram
actor "Card Holder" as holder
entity "POS Terminal" as POS

entity "Mobyyou" as mobyyou
participant "xpay" as xpay
participant "Acquirer" as Acq
participant "Issuer" as issuer
holder->POS: user checks in to the Grab&Go store
POS-> xpay: 1 cent transaction
xpay ->Acq: 1 cent transaction
Acq -> issuer : ISO100 message [authorization]
issuer -> Acq : ISO110 message [authorization response]
Acq -> xpay: authorization response
xpay-> mobyyou : authorization response {transactionId, userid}
mobyyou->mobyyou: get IBAN , create mandate
mobyyou->mobyyou : calculate amount
mobyyou->xpay : initiate sepadd /colection {mandateid , amount}
xpay->xpay: validators , business rules , add transaction to file
xpay-->mobyyou : {success}
xpay-->xpay : create payment 008.001 file
xpay-->Finxp : batch payment file (scheduled job)
Finxp--> Finxp : process batch file
Finxp->xpay: Report file
xpay->xpay : process reporting file , update transaction status
xpay-> mobyyou : send transaction status notification

xpay-->xpay : create payment 002.001 file  (CT transactions)
Finxp-->Finxp : process payment order
Finxp -> mobyyou: Report File
xpay->xpay : process reporting file , update transaction status
xpay-> mobyyou : send transaction status notification


@enduml