drop table if exists transactions;
CREATE TABLE transactions
(
    id                               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id                   VARCHAR(255)                                        NOT NULL,
    transaction_type                 VARCHAR(255)                                        NOT NULL,
    external_transaction_id          INTEGER,
    sender_id                        BIGINT,
    received_id                      BIGINT,
    execution_date                   date,
    amount                           DECIMAL,
    currency                         VARCHAR(255),
    scheduled_execution_date         timestamp,
    end_to_end_transaction_reference VARCHAR(255),
    status                           VARCHAR(255),
    additional_info                  VARCHAR(255),
    remittance_info                  VARCHAR(255),
    processing_status                VARCHAR(255),
    creation_date                    timestamp,
    last_updated                     timestamp,
    authorisation_1_code             VARCHAR(255),
    internal_transaction_reference   VARCHAR(255),
    account_information              text,
    mandate_information              text,
    nature                           VARCHAR(255)
);

ALTER TABLE transactions
drop
constraint if exists uc_transactions_external_transaction,
    ADD CONSTRAINT uc_transactions_external_transaction UNIQUE (external_transaction_id);

ALTER TABLE transactions
drop
constraint if exists FK_TRANSACTIONS_ON_SENDER,
    ADD CONSTRAINT FK_TRANSACTIONS_ON_RECEIVED FOREIGN KEY (received_id) REFERENCES merchant (merchant_id);

ALTER TABLE transactions
drop
constraint if exists FK_TRANSACTIONS_ON_SENDER,
    ADD CONSTRAINT FK_TRANSACTIONS_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (customer_id_identifier);