

app:
  name: henripay-api
  db:
    provider: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    driverClassName: org.postgresql.Driver
    database: henripay
    username: henripay
    password: henripay
    host: localhost
    port: 5432
    show-sql: true
    hibernate:
      ddl-auto: none
    liquibase:
      enabled: true
  camunda.bpm:
    client:
      base-url: http://localhost:8082/engine-rest
      max-tasks: 100
    basic-auth:
      username: demo
      password: demo

management:
  endpoints:
    web:
      exposure:
        include: '*' # ['configprops', 'env', 'health', 'info', 'logfile', 'loggers', 'prometheus', 'threaddump']

logging:
  level:
    com.henripay.henripayapi: DEBUG
#    org.springframework.web.client: INFO
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
