@startuml
'https://plantuml.com/sequence-diagram

actor "Account Holder" as holder
entity "service provider/partner" as mobyyou
participant "xpay Engine" as xpay
participant "Mandate Service" as mandateService
participant "User service" as userservice
participant "Encryption service" as encryptionService
entity "KYC/AML service [xpay/EMI Partner]"  as idCheck
holder -> mobyyou : Authorize (recurrent) payment
mobyyou -> xpay : Add Mandate {accountInfo ,merchantInfo authorization form}
xpay -> xpay : validations , business rules
xpay -> "PSD2 service" : account check
alt
xpay --> idCheck : KYC/AML check
end
xpay -> userservice: add user
userservice -> encryptionService: Encrypt user info
encryptionService--> userservice: encrypted user info
userservice -> userservice : Persist user
xpay -> mandateService: add Mandate
mandateService -> encryptionService : encrypt account info
encryptionService --> mandateService: encrypted accountInfo
mandateService-->mandateService: persist mandate
xpay -->mobyyou: add mandate {success}

@enduml