@startuml
'https://plantuml.com/sequence-diagram
actor "Card Holder" as holder
entity "Merchant" as merchant
entity "service provider/partner" as mobyyou
participant "xpay Engine" as xpay
participant "Spell"
participant "Issuer" as issuer
holder->merchant: user enters credit card details
merchant-> mobyyou: add transaction
mobyyou->xpay: add credit card transaction (recurring)
xpay->xpay: validators , business rules
xpay-> "Spell": /purchace/userinfo
"Spell"--> xpay : {direct_post_url}
xpay->"Spell": direct_post_url/purchase {(recurring)}
"Spell"->"Spell": processing checks...
"Spell"-> issuer: authroization request
issuer --> "Spell" : authorization response
"Spell"-->xpay: transaction completion {sucess}
xpay->"Spell": /direct_post_url/charge {delayed}
xpay-->mobyyou: transaction completion

@enduml