@startuml
'https://plantuml.com/sequence-diagram
autonumber
MobeyU->HPEngine: add Credit Transfer
HPEngine->HPEngine: execute rules
HPEngine-> RaboISO20022 : add Credit Transfer transaction
HPEngine-> MobeyU: Success
RaboISO20022-->RaboISO20022: create payment 002.001 file
RaboISO20022-> Bank: batch payment file (scheduled job)
Bank--> Bank : process payment order
Bank ->RaboISO20022 : Reporting Information
RaboISO20022 --> RaboISO20022 : update transaction status
HPEngine --> RaboISO20022 : get transaction status
RaboISO20022-->HPEngine : transaction status (success)

@enduml