@startuml
'https://plantuml.com/sequence-diagram

autonumber
"Account Holder" -> Bank : Initiate Refund (recurrent) payment
Bank -> "Account Holder" : Fund Return
Bank --> RaboISO20022: Reporting Info (CAMT.52 with Reject Code REFUNED)
BankInterface--> BankInterface: Process reports
HPEngine-> RaboISO20022: get Transaction status
HPEngine-> HPEngine : execute rules
HPEngine--> MobeyU : Refund Notification
HPEngine--> RaboISO20022: add Direct debit Business (Refund)
RaboISO20022->Bank : batch payment file (scheduled job)
Bank-->Bank: process payment
Bank->RaboISO20022: Reporting Information
BankInterface-->RaboISO20022 : update transaction status
HPEngine-> RaboISO20022 : get Transaction status
RaboISO20022-->HPEngine : transaction status (success)


@enduml