@startuml
left to right direction

package RaboBank{
usecase "process direct debit" as UC9
usecase "process Credit transfer" as UC10
usecase "Refund Payment"  as UC11
usecase "Reporting information" as UC12
actor Customer1
}
package Users {
  entity MobeyU as c
  entity RaboPSP as rabo
  actor "Customer" as Customer
}
package HPEngine{

  usecase "process Mandate" as processmandate
  usecase "process Credit transfer" as UC3
  usecase "Process Direct Debit" as UC4
  usecase "Transactions Report" as UC4a
  

}
package MandateService{
  usecase "add Mandate" as addmandate
  usecase "retreive mandate"
  usecase "Revoke Authorization" as UC2
  }

package UserService{
  usecase "add User"
  usecase "retreive account details"
}
package RaboISO20200{
  usecase "CRUD Transactions" as UC5
  usecase "batch processing"  as UCbp
}


Customer --> rabo: 1 cent transaction
processmandate-->addmandate : store mandate details
processmandate-->"add User": store account details
c-->processmandate : account/user info
c -->UC3 : add credit transfer
c -->UC4:  add direct debit
UC4-->UC4 : Execute Rules
UC4-->"retreive account details": get account info
UC4-->"retreive mandate" :get mandate info
UC3-->UC3 : Execute Rules
UC4-->UC5 : add Direct Debit transaction
UC4a-->UC5: get transaction status
UC3-->UC5 : add Credit transfer transaction
UCbp-->UC9: direct debit file
UCbp-->UC10: credit order file
UC12-->UCbp :process reporting file
Customer1-->UC11: refund payment (banking app)
UC4a-->UC5 : add Direct Debit from business (Refund)
UC4a-->UC4a: execute rules
UC4a-->c:refund/reject notifcation
@enduml