
app:
  database:
    url: "sepadd-test-database.eur3.firebasedatabase.app"
    name: "sepadd-test-database"
    test: asa

my:
  test:
    value: test
spring:
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: local
