@startuml
'https://plantuml.com/sequence-diagram


"Account Holder" -> Business : Authorize (recurrent) payment
Business -> SepaDDEngine : Add (Recurrent) Direct Debit Request {accountInfo , authorization form}
SepaDDEngine --> Business: Aknowledge
SepaDDEngine--> SepaDDEngine: process Request
SepaDDEngine-> BankInterface: Add Direct Debit Transaction
BankInterface-->BankInterface : create payment 008.001 file
BankInterface->Bank : batch payment file (scheduled job)
Bank-->Bank: process payment
Bank->BankInterface: Reporting Information
BankInteface-->BankInterface : update transaction status
SepaDDEngine-> BankInterface : get Transaction status
BankInterface-->SepaDDEngine : transaction status (success)


@enduml