openapi: "3.0.0"
info:
  title: "Merchant"
  description: Customer Resources
  version: "1.0.0"

servers:
  - url: 'http://localhost:8080/api'

paths:
  /merchant:
    post:
      summary: Save Merchant
      operationId: saveMerchant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantDTO'
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantDTO'
    get:
      summary: Get Merchant
      operationId: getMerchants
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantDTOList'

  /merchant/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Retrieve a specific merchant by ID
      operationId: getMerchantById
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantDTO'
              example:
                merchantId: 1
                merchantName: "Merchant 1"
                merchantAddress: "Address 1"
                merchantIban: "IBAN1"
                merchantCode: "Code1"
                metadataId: 1
                aggregatorId: 1
        '404':
          description: Merchant not found
    put:
      summary: Update a specific merchant by ID
      operationId: updateMerchantById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantDTO'
            example:
              merchantName: "Updated Merchant"
              merchantAddress: "Updated Address"
              merchantIban: "Updated IBAN"
              merchantCode: "Updated Code"
              metadataId: 1
              aggregatorId: 1
      responses:
        '200':
          description: Merchant updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantDTO'
              example:
                merchantId: 1
                merchantName: "Updated Merchant"
                merchantAddress: "Updated Address"
                merchantIban: "Updated IBAN"
                merchantCode: "Updated Code"
                metadataId: 1
                aggregatorId: 1
        '404':
          description: Merchant not found

    delete:
      summary: Delete a specific merchant by ID
      operationId: deleteMerchantById
      responses:
        '204':
          description: Merchant deleted successfully
        '404':
          description: Merchant not found
  /users:
    get:
      summary: List all users
      operationId: getUsers
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTOList'
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
  /users/{customerIdIdentifier}:
    parameters:
      - in: path
        name: customerIdIdentifier
        required: true
        schema:
          type: integer
    get:
      summary: Get a user by ID
      operationId: getUserById
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
    put:
      summary: Update a user
      operationId: updateUser

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
    delete:
      summary: Delete a user
      operationId: deleteUser
      responses:
        '204':
          description: Successful response
components:
  schemas:
    MerchantDTO:
      type: object
      description: d
      properties:
        merchantId:
          type: string
        merchantName:
          type: string
        merchantAddress:
          type: string
        merchantIban:
          type: string
        merchantCode:
          type: string
        metadata:
          type: integer
        aggregator:
          type: integer
    MerchantDTOList:
      type: array
      items:
        $ref: '#/components/schemas/MerchantDTO'
    Error:
        type: object
        properties:
          code:
            type: integer
            format: int32
          message:
            type: string
    UserDTO:
      type: object
      properties:
        customerIdIdentifier:
          type: integer
        iban:
          type: string
        fullName:
          type: string
        token:
          type: string
        address:
          type: string
        activationDate:
          type: string
          format: date-time
    UserDTOList:
      type: array
      items:
        $ref: '#/components/schemas/UserDTO'
