@startuml
'https://plantuml.com/sequence-diagram
autonumber

mobyyou->"xpay Engine": add Credit Transfer
"xpay Engine"->"xpay Engine": execute rules
"xpay Engine"-> RaboISO20022 : add Credit Transfer transaction
"xpay Engine"-> mobyyou: Success
RaboISO20022-->RaboISO20022: create payment 002.001 file
RaboISO20022-> Bank: batch payment file (scheduled job)
Bank--> Bank : process payment order
Bank ->RaboISO20022 : Reporting Information
RaboISO20022 --> RaboISO20022 : update transaction status
"xpay Engine" --> RaboISO20022 : get transaction status
RaboISO20022-->"xpay Engine" : transaction status (success)

@enduml