@startuml
'https://plantuml.com/sequence-diagram

autonumber

Bank->RaboISO20022: Reporting Information (Reject)

RaboISO20022-->RaboISO20022 : update transaction status
Bank->RaboISO20022: Reporting Information (Reject)
"xpay Engine"-> RaboISO20022 : get Transaction status
"xpay Engine"-> "xpay Engine": execute rules
loop x times
"xpay Engine" ->RaboISO20022 : Add Direct Debit (Retry)
end
"xpay Engine" -> mobyyou: Reject Notification

@enduml