@startuml
'https://plantuml.com/sequence-diagram

autonumber
"Customer" -> Bank : Initiate Refund (recurrent) payment
Bank -> "Customer" : Fund Return
Bank --> RaboISO20022: Reporting Info (CAMT.52 with Reject Code REFUNDED)
RaboISO20022--> RaboISO20022: Process reports
"xpay Engine"-> RaboISO20022: get Transaction status
"xpay Engine"-> "xpay Engine" : execute rules
"xpay Engine"--> mobyyou : Refund Notification
"xpay Engine"--> RaboISO20022: add Direct debit Business (Refund)
RaboISO20022->Bank : batch payment file (scheduled job)
Bank-->Bank: process payment
Bank->RaboISO20022: Reporting Information
RaboISO20022-->RaboISO20022 : update transaction status
"xpay Engine"-> RaboISO20022 : get Transaction status
RaboISO20022-->"xpay Engine" : transaction status (success)


@enduml