name: HenriPay CI with Maven

on:
  push:
    branches: [ "feature/HEN-CI" ]

jobs:
  build-maven:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - uses: actions/checkout@v3
        with:
          repository: 'HenriPay/henripay-parent.git'
          ref: '3.2.3'
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Install parent project
        run: mvn clean install

      - uses: actions/checkout@v3
        with:
          repository: 'HenriPay/henripay-parent.git'
          ref: '3.1.10'
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Install parent project
        run: mvn clean install

      - uses: actions/checkout@v3
      - name: Clean with Maven
        run: mvn clean
      - name: Compile with Maven
        run: mvn compile
      - name: Build with Maven
        run: mvn install

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      #TODO: registry
      #- name: Tag Docker image
      #  run: docker tag your-image-name your-registry/your-image-name:v1.0.0
      #- name: Push Docker image
      #  run: docker push your-registry/your-image-name:v1.0.0
